site_name: Docking Station

nav:
  - Home: "index.md"
  - About: "about.md"
  - Planning:
    - Process: "a1_planning_process.md"
    - Products: "a1_planning_products.md"
  - Configuring: 
    - Process: 
      - Design Principles: "a2_configuring_process_designprinciples.md"
      - Voxelsize: "a2_configuring_process_voxelsize.md"
    - Products: "a2_configuring_products.md"
  - Massing: "a3_massing.md"
  - Forming: "a4_forming.md"
  - Index:
      - Scripts: "index/scripts.md"
        - Step 1.1 Voxelization high resolution:
        - Step 1.2 Voxelization low resolution:
        - Step 2.1 Solar envelope:
        - Step 2.2 Shaping:
        - Step 2.3 Visualization solar envelope:
        - Step 3.1 Skyview:
        - Step 3.2 Noise field from street:
        - Step 3.3 Distance to entrance:
        - Step 3.4 Distance to facade:
        - Step 4 Interpolation Skyview:
        - Step 4 Interpolation sun access:
        - Step 4 Interpolation sun blockage:
        - Step 6.1 ABM Growth model:
        - Step 6.2 Visualization ABM model:
        - Step 7 Shafts and corridors:
        - Step 8.1 Poligonization Facade:
        - Step 8.2 Poligonization structure:
      - Figures: "index/figures.md"
      - Presentations: "index/presentations.md"
      - Bibliography: "index/bibliography.md"
  - Documenting (TBR):
      - Instructions: "documenting/instructions.md"
      - Folder Structure: "documenting/folder_structure.md"
      - Guidelines: "documenting/guidelines.md"

theme:
  name: material
  palette: 
    scheme: 
    primary: blue grey
    accent: light blue
  font:
    text: Montserrat
  logo: img/favicon.png


markdown_extensions:
  - codehilite
  - pymdownx.keys
  - pymdownx.highlight
  - pymdownx.emoji
