site_name: Docking Station

nav:
  - Home: "index.md"
  - About: "about.md"
  - Planning:
    - Process: "a1_planning_process.md"
    - Products: "a1_planning_products.md"
  - Configuring: 
    - Process: 
      - Design Principles: "a2_configuring_process_designprinciples.md"
      - Voxelsize: "a2_configuring_process_voxelsize.md"
    - Products: "a2_configuring_products.md"
  - Massing: "a3_massing.md"
  - Massing_test:
    - Process: 
      - Intro: "a3_massing_intro.md"
      - Spatial Analysis: "a3_massing_sa.md"
      - Shaping: "a3_massing_shaping"
      - ABM: "a3_massing_abm.md"
      - Shafts and corridors: "a3_massing_shafts_corridors.md"
  - Forming: "a4_forming.md"
  - Index:
      - Scripts: 
        - Step 1.1 Voxelization high resolution: "Notebooks/s1.1_voxelization_highres.ipynb"
        - Step 1.2 Voxelization low resolution: "Notebooks/s1.2_voxelization_lowres.ipynb"
        - Step 2.1 Solar envelope: "Notebooks/s2.1_solar_envelope.ipynb"
        - Step 2.2 Shaping: "Notebooks/s2.2_shaping.ipynb"
        - Step 2.3 Visualization solar envelope: "Notebooks/s2.3_visualisation_solarenv.ipynb"
        - Step 3.1 Skyview: "Notebooks/s3.1_Skyview.ipynb"
        - Step 3.2 Noise field from street: "Notebooks/s3.2_Noise_field_from_street.ipynb"
        - Step 3.3 Distance to facade: "Notebooks/s3.3_distance_to_facade.ipynb"
        - Step 3.4 Distance to entrance: "Notebooks/s3.4_distance_to_entrance.ipynb"
        - Step 4 Interpolation Skyview: "Notebooks/s4_interpolation_skyview.ipynb"
        - Step 4 Interpolation sun access: "Notebooks/s4_interpolation_sun_access.ipynb" 
        - Step 4 Interpolation sun blockage: "Notebooks/s4_interpolation_sun_blockage.ipynb"
        - Step 6.1 ABM Growth model: "Notebooks/s6.1_ABM_growth.ipynb"
        - Step 6.2 Visualization ABM model: "Notebooks/s6.2_ABM_visual.ipynb"
        - Step 7 Shafts and corridors: "Notebooks/s7_Shafts_corridors.ipynb"
        - Step 8.1 Polygonization Facade: "Notebooks/s8.1_polgonization_facade2.ipynb"
        - Step 8.2 Polygonization structure: "Notebooks/s8.2_polgonization_structure.ipynb"
      - Figures: "index/figures.md"
      - Presentations: "index/presentations.md"
      - Bibliography: "index/bibliography.md"
  - Documenting (TBR):
      - Instructions: "documenting/instructions.md"
      - Folder Structure: "documenting/folder_structure.md"
      - Guidelines: "documenting/guidelines.md"

theme:
  name: material
  palette: 
    scheme: 
    primary: blue grey
    accent: light blue
  font:
    text: Montserrat
  logo: img/klein.png


markdown_extensions:
  - codehilite
  - pymdownx.keys
  - pymdownx.highlight
  - pymdownx.emoji

plugins:
  - mknotebooks
